# Enhanced Vietnamese Summarization Configuration

model:
  base_model: "VietAI/vit5-large-vietnews-summarization"
  max_input_length: 512
  max_output_length: 128
  enhancements:
    coverage_loss_weight: 1.0
    pointer_gen_loss_weight: 1.0

data:
  preprocessing:
    normalize_unicode: true
    remove_special_chars: false
    min_input_length: 50
    max_input_length: 512
    min_summary_length: 10
    max_summary_length: 128

training:
  batch_size: 4
  learning_rate: 5e-5
  num_epochs: 3
  weight_decay: 0.01
  warmup_steps: 100
  gradient_clipping: 1.0
  curriculum_learning: false

evaluation:
  metrics: ["rouge", "bleu"]

hardware:
  device: "auto"  # auto, cpu, cuda
  mixed_precision: false
